services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: quick-flayer-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: quick_flayer_db
      POSTGRES_USER: quick_flayer_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dev_password}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - quick-flayer-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quick_flayer_user -d quick_flayer_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin (Database Management UI)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: quick-flayer-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@quickflayer.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - quick-flayer-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  quick-flayer-network:
    driver: bridge
